#! /bin/bash

clear

echo "----------------------------------------------------------------------------------------------"
echo "Write"

if [ -z "$1" ]
then
	./write_sharmem ./test.txt
else
	./write_sharmem $#
fi
