#! /bin/bash

clear

echo "----------------------------------------------------------------------------------------------"
echo "Read"

if [ $# -eq 0 ]
then
	./read_sharmem
else
	./read_sharmem $#
fi
